### ISSUE TITLE
Wanna incorporate flow support into node-tap?

### ISSUE THREAD

**Issue by isaacs** [newtang/flow-tap#1]
Hey, I stumbled across this neat little connector module, and wondered why not just add a `--flow` flag to node-tap to tell it to load `flow-node` directly?

It could work similar to how TypeScript is supported.  Basically, `--flow` could just trigger it to add `['--require', 'flow-remove-types/register']` to the node args.

I'd do it myself, but I felt some ways about basically stomping on your first npm module that you took the time to blog about and all, so thought I'd offer it up as a good first contribution to node-tap :)

**Comment by newtang** [comment]
Hi, @isaacs, that's so nice of you!  Sure, I'd be happy to take a crack at contributing it to node-tap.

**Comment by isaacs** [comment]
Cool! You can add the `--flow` option in `bin/jack.js`, and then use the option in `bin/run.js` to add the appropriate node arg if it's set. Copy the test at `test/run/ts.js` and modify to test the new functionality.

**Comment by newtang** [comment]
@isaacs I gave it a try, but I'm running into some problems. Could you help?

Simplified:
In jack.js
```
flow: flag({
    alias: '--node-arg=--flow',
    description: `Removes flow types`,
})
```

In run.js
```
if(options.flow){
        debug('flow', file)
        const args = [
          ...(options['node-arg']),
          flowNode,
          file,
          ...(options['test-arg']),
        ]
        tap.spawn(node, args, opt, file)
      } 
```

In a test:
```
t.test('flow', t => {
  const ok = tmpfile(t, 'flow/ok.js', `
    // @flow
    const t = require(${tap})
    function square(n: number): number {
      return n * n;
    }
    t.pass('this is fine')
  `)

  const args = [ok, '--flow']
  // const args = [ok, '--node-arg=--require', '--node-arg=flow-remove-types/register']


  run(args, {}, (er, o, e) => {
    t.equal(er, null)
    t.matchSnapshot(o)
    t.end()
  })
})
```

The test recognizes "flow" as a valid option, but it doesn't seem to run any of my code in the `if(options.flow)` block within `run.js`. Sorry, I know you could do this in like 2 seconds, but I'm clearly missing something. 

If it's easier I can push my branch.

**Comment by isaacs** [comment]
Ah yeah. Don't mark it as an alias. Just add the node arg in run.js if options.flow is set.

**Comment by newtang** [comment]
@isaacs Ah, yes. Thank you!
